default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: TaskMgmt_development

test:
  <<: *default
  database: TaskMgmt_test

production:
  <<: *default
  database: TaskMgmt_production
  username: TaskMgmt
  password: <%= ENV['TaskMgmt_DATABASE_PASSWORD'] %>
